import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { ActiveProvider } from "@/components/providers/ActiveProvider";
import { cn } from "@/utils/cn";

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="h-full bg-black">
      <body className={cn(montserrat.className, "h-full antialiased")}>
        <ActiveProvider>{children}</ActiveProvider>
      </body>
    </html>
  );
};

export default RootLayout;
